export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SAVE_INGREDIENT = 'SAVE_INGREDIENT';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
export const PURCHASE_BURGER_SUCCEEDED = 'PURCHASE_BURGER_SUCCEEDED';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';